### ISSUE TITLE
Thanks for open source. Two issues.

### ISSUE THREAD

**Issue by tlerbao** [varrcan/oceanic-dark-theme#1]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/20442232/170169310-f866e2b4-f273-4c42-9766-c922ba4c8ea5.png">

1. The background color of the horizontal scroll bar is incorrect, it should be transparent.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/20442232/170169507-cc250a2a-f15b-4b2d-acc3-19c6114c9228.png">

2. In the sidebar, the background color of some special directories feels a bit awkward and not very good-looking. Can you provide cancellation or customization.

<img width="1972" alt="image" src="https://user-images.githubusercontent.com/20442232/170172183-155a0d2c-1314-4cba-8183-4fa7def767dc.png">

3. The background color of phpstorm just started does not match the theme color, I hope it can be fixed.

**Comment by varrcan** [comment]
> 

Thanks for the feedback! Could you clarify the build number of your IDE? 
You can find it in the menu: Help - About.

For example:
Build #PS-221.5591.58, built on May 12, 2022

**Comment by tlerbao** [comment]
> > 
> 
> Thanks for the feedback! Could you clarify the build number of your IDE? You can find it in the menu: Help - About.
> 
> For example: Build #PS-221.5591.58, built on May 12, 2022

<img width="541" alt="image" src="https://user-images.githubusercontent.com/20442232/170276452-8e2c67c1-4598-4bcf-a8d7-212d03e4f76c.png">

**Comment by varrcan** [comment]
It's strange, but I can't reproduce the problem with scrolling. I'll try to test it on a clean IDE of different versions and on different OS, maybe it will be possible to reproduce it.

I will keep you informed

**Comment by tlerbao** [comment]
@varrcan Thank you for taking the time to answer. I also want to try to make a set of colors that I like. I want to use your project as a starting template. I have installed IntelliJ IDEA, and successfully modified the color and previewed it successfully, but I am a PHPer, I don't know Java at all, no I know how to export the modified result, or build it into a plugin that can be installed. If you have time, I hope you can guide me roughly how to build the project.

**Comment by varrcan** [comment]
> @varrcan Thank you for taking the time to answer. I also want to try to make a set of colors that I like. I want to use your project as a starting template. I have installed IntelliJ IDEA, and successfully modified the color and previewed it successfully, but I am a PHPer, I don't know Java at all, no I know how to export the modified result, or build it into a plugin that can be installed. If you have time, I hope you can guide me roughly how to build the project.

To build a plugin from source files, knowledge of Java is not necessary, everything is done directly from the IDE interface. You need a Gradle plugin and java installed on the system for this.
And there you can immediately view the changes you have made in live-mode. 

After the plugin is built (it will be built .jar file), you can install the plugin in the IDE directly from the disk

![img2505202270fc](https://user-images.githubusercontent.com/23196073/170284231-ac8e8613-de34-4670-8b26-2d20ee5ceb91.png)

![img250520221dc3](https://user-images.githubusercontent.com/23196073/170282896-48cc267c-66ab-4554-abfe-2c80d4324828.png)

**Comment by tlerbao** [comment]
@varrcan thanks, Where can I get the latest and complete settings for theme.json。all parameters of the ui object.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/20442232/170303292-9631b37a-fa8f-4c1a-a1b8-15465ae518ce.png">

**Comment by varrcan** [comment]
unfortunately, I did not find such information, but all the parameters are available in the autocomplete ctrl+space

**Comment by tlerbao** [comment]
@varrcan  Hello, I have reported these three problems, have you found a solution? If you can solve these three problems, then it will be perfect, thank you very much.

**Comment by varrcan** [comment]
> @varrcan Hello, I have reported these three problems, have you found a solution? If you can solve these three problems, then it will be perfect, thank you very much.

Hello. There will be a small update in a couple of days, which should fix the problem with the sidebar.

**Comment by varrcan** [comment]
On the second point. This is the standard behavior of the IDE, you can turn off the highlighting of the tests folder in the settings
![img03072022918b](https://user-images.githubusercontent.com/23196073/177046920-f38cb630-7dc7-4333-8660-38666f1bb487.png)

On the third point. I didn't find an option to change the background color when starting the IDE. If I succeed in the future, I will definitely change it.

Thank you for your feedback!

**Comment by tlerbao** [comment]
@varrcan The issue that the background color of the horizontal scroll bar is not transparent has not been fixed.

**Comment by varrcan** [comment]
> @varrcan The issue that the background color of the horizontal scroll bar is not transparent has not been fixed.

hmm, maybe this is a feature of the OS. are you using a Mac? can you tell the version?

**Comment by tlerbao** [comment]
@varrcan 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/20442232/178096832-da58d5a1-84c1-4f16-8442-7a08eef016fa.png">
<img width="757" alt="image" src="https://user-images.githubusercontent.com/20442232/178096839-74d0510a-2232-48cb-b442-63135f2f10b5.png">
