### ISSUE TITLE
Please be compatible with the new UI of WebStorm 2022.3

### ISSUE THREAD

**Issue by tlerbao** [varrcan/oceanic-dark-theme#2]
WebStorm releases 2022.3 with new UI

But there seems to be some compatibility issues

https://user-images.githubusercontent.com/20442232/205243305-f1083cd7-b798-4254-8d36-7dfefbe08c5e.mp4

**Comment by tlerbao** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/20442232/205243563-2b9bd23e-92bb-4323-a6cb-46d6b75a3bc8.png">

There is also the problem of the background color of the horizontal scroll bar of the editor that has not been resolved

**Comment by varrcan** [comment]
This is not a bug. You can change the template to a standard one and see the same behavior.

Unfortunately, I can't reproduce the scrolling problem. Tested on mac OS, Windows, Linux - there is no such problem anywhere. I also asked to check my colleagues and friends, no one can detect such a bug.


Maybe you still have a residual configuration from the previous theme and now it affects the current theme.
As an experiment, try installing another theme, for example, this one https://plugins.jetbrains.com/plugin/8006-material-theme-ui
Does the scroll error persist?

**Comment by tlerbao** [comment]
<img width="987" alt="image" src="https://user-images.githubusercontent.com/20442232/206195541-aae4d642-c889-4546-8891-97c2b7c3ffcf.png">
@varrcan I tested other themes, but there is still the problem that the background of the horizontal scroll bar is not transparent. How can I solve this problem?

**Comment by tlerbao** [comment]
The non-transparent background of the horizontal scroll bar has been confirmed with the official as a bug.
