### ISSUE TITLE
Compatibility with IDEA build 231.x.x

### ISSUE THREAD

**Issue by muriloschuck** [varrcan/oceanic-dark-theme#3]
Hi!

Firstly, thanks for open sourcing this. From a lot of themes, this became my favorite one and works like a charm.

Could you please update this to be compatible with build 231.x.x and to work with new UI from 2023.1? It would be very nice as I'm at 2022.3 to keep working with oceanic dark. 

Thanks!

**Comment by varrcan** [comment]
Hi! Thank you for pointing out the compatibility bug.
I have updated all the plugin dependencies, now it has build support up to IU-233.*

The plugin is currently undergoing moderation (it takes about one or two days), but you can install it manually from the jar file by downloading the new release from the page [GitHub](https://github.com/varrcan/oceanic-dark-theme/releases/tag/1.1.6) or [JB marketplace](https://plugins.jetbrains.com/plugin/16506-oceanic-dark-theme/versions/stable/313889)

Thanks for the feedback, I am pleased that this theme has become your favorite :)

**Comment by muriloschuck** [comment]
Thanks, it's working with new theme
