### ISSUE TITLE
In the new UI, the color of the relevant buttons running in the upper right corner is very striking.

### ISSUE THREAD

**Issue by tlerbao** [varrcan/oceanic-dark-theme#5]
<img width="613" alt="CleanShot 2023-04-21 at 17 33 56@2x" src="https://user-images.githubusercontent.com/20442232/233602425-5c4466b7-1d3d-4831-a7ec-821220633c63.png">

In the new UI, the color of the relevant buttons running in the upper right corner is very striking. I hope to optimize it.

**Comment by varrcan** [comment]
It looks like the color of the icons will not be able to control, I did not find such an opportunity, only to replace them with others.
Maybe the [Aton Material Icons](https://plugins.jetbrains.com/plugin/10044-atom-material-icons) plugin will solve your problem?
