### ISSUE TITLE
Unused variable style missing? 

### ISSUE THREAD

**Issue by jameschetwood** [varrcan/oceanic-dark-theme#6]
If I use the default theme I have different stying when a variable isnt being used: 

<img width="733" alt="image" src="https://github.com/varrcan/oceanic-dark-theme/assets/6142418/f517d540-4d46-4761-b511-76b31ebdd2ff">

I dont have this with the Oceanic Dark Theme: 

<img width="733" alt="image" src="https://github.com/varrcan/oceanic-dark-theme/assets/6142418/44972fa4-2b53-472c-9f9d-50ed02dcda6d">

**Comment by varrcan** [comment]
The theme does not set this parameter, but inherits the standard IDE value.

Most likely, you had the option disabled, the theme inherited this value, and unused variables were not highlighted. At the same time, the standard Darcula theme forcibly sets its value.

At your request, I have also set this option forcibly. But you can always edit this value in the settings. 

Currently, the plugin is undergoing moderation (it takes about one to two days), but you can install it manually from the jar file by downloading a new version from the [GitHub](https://github.com/varrcan/oceanic-dark-theme/releases/tag/1.1.7) or [JB marketplace](https://plugins.jetbrains.com/plugin/16506-oceanic-dark-theme/versions/stable/392052) page

![img08092023c07f](https://github.com/varrcan/oceanic-dark-theme/assets/23196073/92d4e566-90b8-4a5f-acf5-2d90ebaf396c)
