### ISSUE TITLE
Theme appearance issue

### ISSUE THREAD

**Issue by skovalevskii** [varrcan/oceanic-dark-theme#7]
Hi. Today I updated your plugin in my PyCharm and after the successful update the theme doesnt apply to my code background anymore. Now it's just completely white. Could you please tell me how to fix this?
<img width="1680" alt="Снимок экрана 2023-09-11 в 16 16 18" src="https://github.com/varrcan/oceanic-dark-theme/assets/17334226/6a3965d7-6a92-4541-aa7d-d0342b77bd21">

**Comment by skovalevskii** [comment]
Im sorry for my stupid question. I still dont know why it has been reseted but I turned it on in Settings->Editor->Color Scheme->General.

**Comment by varrcan** [comment]
Hi! Yes, sometimes this happens when updating, the theme is reset to the standard one. 
You just need to go to settings - editor - color scheme, and select a Oceanic Dark Theme

![img110920233f7a](https://github.com/varrcan/oceanic-dark-theme/assets/23196073/56f408cb-7c0e-4e02-8772-1f55ac51804e)
