### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by AminRst** [varrcan/oceanic-dark-theme#8]
Hi
After the last update my theme is not dark anymore
It is LIGHT

**Comment by varrcan** [comment]
Hi! Yes, sometimes this happens when updating, the theme is reset to the standard one. 
You just need to go to settings - editor - color scheme, and select a Oceanic Dark Theme

![img110920233f7a](https://github.com/varrcan/oceanic-dark-theme/assets/23196073/56f408cb-7c0e-4e02-8772-1f55ac51804e)

**Comment by AminRst** [comment]
ohhhhhhhhh
Thank you so much
I love this theme
