### ISSUE TITLE
Bug：“Refactor -> Move” UI display abnormal

### ISSUE THREAD

**Issue by tlerbao** [varrcan/oceanic-dark-theme#9]
The following is the built-in theme, there are no issues.
![CleanShot 2024-05-01 at 18 37 45@2x](https://github.com/varrcan/oceanic-dark-theme/assets/20442232/4fb393ef-79c0-4a8e-a03e-b346baad38c3)

The oceanic-dark-theme has issues.

![CleanShot 2024-05-01 at 18 39 21@2x](https://github.com/varrcan/oceanic-dark-theme/assets/20442232/31fec7aa-3075-460a-adcc-d76c55aa404b)

**Comment by varrcan** [comment]
Thank you for your feedback! I have corrected the display of the table in the pop-up window, version 1.1.9 is currently being checked by Jetbrains. Alternatively, you can download the jar file from the release page https://github.com/varrcan/oceanic-dark-theme/releases/tag/1.1.9


![img0205202428c7](https://github.com/varrcan/oceanic-dark-theme/assets/23196073/4a403919-bd5d-491e-86ae-82247c94c82f)
